alter table users
    alter column id ADD GENERATED BY DEFAULT AS IDENTITY;

alter table roles
    alter column id ADD GENERATED BY DEFAULT AS IDENTITY;

alter table profiles
    alter column id ADD GENERATED BY DEFAULT AS IDENTITY;